#!/bin/bash
set -e

export DEBIAN_FRONTEND=noninteractive

cd /root

# Install dependencies
apt-get update
apt-get -y install $TARSNAP_RUN_PACKAGES $TARSNAP_MAKE_PACKAGES

echo en_US.UTF-8 UTF-8 > /etc/locale.gen
locale-gen

# Download and verify
wget --quiet https://www.tarsnap.com/download/tarsnap-autoconf-$TARSNAP_VERSION.tgz
echo "$TARSNAP_SHA256  tarsnap-autoconf-$TARSNAP_VERSION.tgz" | sha256sum --check --strict --quiet


# Install tarsnap
tar zxf tarsnap-autoconf-$TARSNAP_VERSION.tgz
(
cd tarsnap-autoconf-$TARSNAP_VERSION || exit
./configure
make all install clean
)

# Clean up
rm -f tarsnap-autoconf-$TARSNAP_VERSION.tgz
rm -rf tarsnap-autoconf-$TARSNAP_VERSION
apt-get -y remove --purge $TARSNAP_MAKE_PACKAGES
apt-get -y autoremove
rm -rf /var/lib/apt/lists/*

# Self-destruct
rm "${BASH_SOURCE[0]}"
